# This workflow will do a clean install of node dependencies,
# build the application and deploy it as latest nightly
# as soon as there are pushes to the main branch

name: Build & Deploy (Nightly)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Build app using Yarn
      run: |
        printf "VUE_APP_FB_API_KEY=${{ secrets.VUE_APP_FB_API_KEY_DEV }}\nVUE_APP_FB_PROJECT_ID=${{ secrets.VUE_APP_FB_PROJECT_ID_DEV }}" >> .env.production.local
        npm install -g yarn
        yarn install
        yarn build
    - name: Push Build files to dev environment
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PASS }}
        scp_source: dist/*
        scp_target: ${{ secrets.DEPLOY_PATH_DEV }}
